services:
  gateway:
    build: .
    container_name: psitest-gateway
    command: fastapi run app --host 0.0.0.0 --port 80
    ports:
      - 8000:80
    networks:
      - psitest
    environment:
      - PSITEST_AUTH=http://auth:80
      - PSITEST_CADASTRO=http://cadastro:80
      - PSITEST_QUESTIONARIOS=http://questionarios:80
      - PSITEST_RESPOSTAS=http://respostas:80
networks:
  psitest:
    external: true
