services:
  gateway:
    build: .
    container_name: psitest-gateway
    command: fastapi run app --host 0.0.0.0 --port 80
    ports:
      - 8000:80
    networks:
      - mynetwork
    env_file: ".env"
networks:
  mynetwork:
    external: true
